version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 50
  ignore:
  - dependency-name: commander
    versions:
    - "> 4.1.0"
  - dependency-name: "@koa/router"
    versions:
    - "> 8.0.8"
  - dependency-name: sharp
    versions:
    - ">= 0.26.a, < 0.27"
  - dependency-name: terser-webpack-plugin
    versions:
    - ">= 5.a, < 6"
  - dependency-name: tslint
    versions:
    - "> 5.20.1"
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - "> 2.33.0"
  - dependency-name: webpack
    versions:
    - 5.19.0
    - 5.20.0
    - 5.20.1
    - 5.24.0
    - 5.24.1
    - 5.24.4
    - 5.26.0
    - 5.26.2
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.31.2
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.36.0
  - dependency-name: aws-sdk
    versions:
    - 2.834.0
    - 2.835.0
    - 2.836.0
    - 2.839.0
    - 2.840.0
    - 2.843.0
    - 2.845.0
    - 2.846.0
    - 2.849.0
    - 2.850.0
    - 2.851.0
    - 2.853.0
    - 2.855.0
    - 2.856.0
    - 2.858.0
    - 2.859.0
    - 2.860.0
    - 2.861.0
    - 2.864.0
    - 2.865.0
    - 2.869.0
    - 2.870.0
    - 2.871.0
    - 2.874.0
    - 2.875.0
    - 2.876.0
    - 2.879.0
    - 2.880.0
    - 2.881.0
    - 2.882.0
    - 2.884.0
    - 2.885.0
    - 2.889.0
    - 2.890.0
    - 2.892.0
    - 2.893.0
    - 2.894.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.24
    - 14.14.32
    - 14.14.36
    - 15.0.0
  - dependency-name: gulp-replace
    versions:
    - 1.1.1
  - dependency-name: ts-loader
    versions:
    - 9.1.0
  - dependency-name: js-yaml
    versions:
    - 4.0.0
    - 4.1.0
  - dependency-name: is-root
    versions:
    - 3.0.0
  - dependency-name: highlight.js
    versions:
    - 10.7.2
  - dependency-name: "@types/js-yaml"
    versions:
    - 4.0.0
  - dependency-name: "@types/sharp"
    versions:
    - 0.28.0
  - dependency-name: sharp
    versions:
    - 0.27.0
    - 0.28.0
    - 0.28.1
  - dependency-name: katex
    versions:
    - 0.13.1
  - dependency-name: "@types/node-fetch"
    versions:
    - 2.5.9
  - dependency-name: systeminformation
    versions:
    - 5.0.11
    - 5.0.6
    - 5.0.8
    - 5.0.9
    - 5.1.2
    - 5.2.1
    - 5.2.6
    - 5.3.0
    - 5.3.1
    - 5.3.2
    - 5.3.5
    - 5.6.5
    - 5.6.9
  - dependency-name: cbor
    versions:
    - 6.0.1
    - 7.0.0
    - 7.0.1
    - 7.0.2
    - 7.0.3
    - 7.0.4
  - dependency-name: "@elastic/elasticsearch"
    versions:
    - 7.10.0
    - 7.11.0
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.5.0
    - 7.6.0
    - 7.7.0
    - 7.8.0
  - dependency-name: vue-i18n
    versions:
    - 8.24.0
  - dependency-name: jsdom
    versions:
    - 16.5.0
  - dependency-name: mocha
    versions:
    - 8.3.0
    - 8.3.1
  - dependency-name: apexcharts
    versions:
    - 3.25.0
  - dependency-name: jsonld
    versions:
    - 3.3.2
    - 5.0.0
  - dependency-name: chai
    versions:
    - 4.3.0
  - dependency-name: pug
    versions:
    - 3.0.0
  - dependency-name: three
    versions:
    - 0.118.3
